name = "CImGui"
uuid = "5d785b6c-b76f-510e-a07c-3070796c7e87"
authors = ["Yupei Qi <qiyupei@gmail.com>"]
version = "1.82.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CSyntax = "ea656a56-6ca6-5dda-bba5-7b6963a5f74c"
ImGuiGLFWBackend = "623d79b3-9695-4e60-bd7e-2a5aabaa6933"
ImGuiOpenGL2Backend = "c105bd9b-9289-4129-acf4-4c081b46d160"
ImGuiOpenGLBackend = "9d0819b4-44e7-43a2-ad03-8fb999128168"
LibCImGui = "9be01004-c4f5-478b-abeb-cb32b114cf5e"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[compat]
CEnum = "0.4"
CSyntax = "0.4"
ImGuiGLFWBackend = "0.1"
ImGuiOpenGLBackend = "0.1"
ImGuiOpenGL2Backend = "0.1"
LibCImGui = "1.82.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
