name = "CImGui"
uuid = "5d785b6c-b76f-510e-a07c-3070796c7e87"
authors = ["Gnimuc <qiyupei@gmail.com>"]
version = "1.69.1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CSyntax = "ea656a56-6ca6-5dda-bba5-7b6963a5f74c"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
