[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CImGuiPack_jll = "333409e9-af72-5310-9767-d6ad21a76a05"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
